{{ if .Values.otelcolSidecar.enabled }}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  mode: sidecar
  config: {{ .Values.otelcolSidecar.config | toYaml | nindent 4 }}
{{ end }}
