{{ if .Values.otelcol.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app: otelcol
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
      {{- include "uptrace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: otelcol
        {{- include "uptrace.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: otelcol
      containers:
        - name: otelcol
          image: otel/opentelemetry-collector-contrib
          args: ['--config', '/etc/config/config.yaml']
          volumeMounts:
            - name: config
              mountPath: /etc/config
          imagePullPolicy: IfNotPresent
          env:
            {{- toYaml .Values.uptrace.env | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: otelcol
{{ end }}
