{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: uptrace-postgresql
spec:
  imageName: {{ .Values.postgresql.imageNname }}
  imagePullSecrets:
    {{- toYaml .Values.postgresql.imagePullSecrets | nindent 4 }}

  instances: {{ .Values.postgresql.instances }}

  storage:
    storageClass: {{ .Values.postgresql.storage.storageClass }}
    size: {{ .Values.postgresql.storage.size }}
{{- end }}
