{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-dante
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.uptrace.config.pg.user | b64enc | quote }}
  password: {{ .Values.uptrace.config.pg.password | b64enc | quote }}
{{- end }}
