{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: uptrace-postgresql
  labels:
    app: clickhouse
    {{- include "uptrace.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.podAnnotations | nindent 4 }}

spec:
  imageName: {{ .Values.postgresql.imageNname }}
  imagePullSecrets:
    {{- toYaml .Values.postgresql.imagePullSecrets | nindent 4 }}

  instances: {{ .Values.postgresql.instances }}

  storage:
    size: {{ .Values.postgresql.storage.size }}
    {{- if .Values.postgresql.storage.storageClass }}
    storageClass: {{ .Values.postgresql.storage.storageClass }}
    {{- end }}
{{- end }}
