{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: uptrace-postgresql
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 3

  storage:
    size: 1Gi

  managed:
    roles:
      - name: {{ .Values.uptrace.config.pg.user }}
        ensure: present
        createdb: true
        login: true
        superuser: true
        passwordSecret:
          name: uptrace-postgresql-secret
{{- end }}
